version: '3.8'

services:
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8000:8000"
    environment:
      - ALDEAMO_SERVICE_URL=http://aldeamo-service:8001
      - TWILIO_SERVICE_URL=http://twilio-service:8002
      - FAILURE_THRESHOLD=5
      - RECOVERY_TIMEOUT=5
      - RESET_TIMEOUT=10
    depends_on:
      - aldeamo-service
      - twilio-service
    networks:
      - microservices-net
    volumes:
      - ./payment-service/app:/app/app

  aldeamo-service:
    build: ./aldeamo-service
    container_name: aldeamo-service
    ports:
      - "8001:8001"
    environment:
      - ALDEAMO_FAILURE_RATE=0.5  # 50% de fallas para pruebas
    networks:
      - microservices-net
    volumes:
      - ./aldeamo-service/app:/app/app

  twilio-service:
    build: ./twilio-service
    container_name: twilio-service
    ports:
      - "8002:8002"
    environment:
      - TWILIO_FAILURE_RATE=0.1  # 10% de fallas para pruebas
    networks:
      - microservices-net
    volumes:
      - ./twilio-service/app:/app/app

networks:
  microservices-net:
    driver: bridge